Name:           ros-melodic-navigation-experimental
Version:        0.3.3
Release:        1%{?dist}
Summary:        ROS navigation_experimental package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/navigation_experimental
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-assisted-teleop
Requires:       ros-melodic-goal-passer
Requires:       ros-melodic-pose-base-controller
Requires:       ros-melodic-pose-follower
Requires:       ros-melodic-sbpl-lattice-planner
Requires:       ros-melodic-sbpl-recovery
Requires:       ros-melodic-twist-recovery
BuildRequires:  ros-melodic-catkin

%description
A collection of navigation plugins and tools: Various recovery behaviors, local
and global planner plugins for move_base, a teleop filter for obstacle
avoidance, a simple control-based move_base replacement etc.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Oct 15 2019 Martin Günther <martin.guenther@dfki.de> - 0.3.3-1
- Autogenerated by Bloom

* Wed Jan 16 2019 Martin Günther <martin.guenther@dfki.de> - 0.3.2-0
- Autogenerated by Bloom

* Wed Sep 05 2018 Martin Günther <martin.guenther@dfki.de> - 0.3.1-0
- Autogenerated by Bloom

* Tue Sep 04 2018 Martin Günther <martin.guenther@dfki.de> - 0.3.0-0
- Autogenerated by Bloom

* Mon Sep 03 2018 Martin Günther <martin.guenther@dfki.de> - 0.2.0-0
- Autogenerated by Bloom

